name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]
    
permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          path: 'main'

      - name: Install Packages & Setup
        run: |
          cd main/
          npm ci
